### ISSUE TITLE
Add Analytics + Tracking

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/mentored.dev#142]
Technologies to use. Either:
- Mixpanel
- Google Analytics 
- something else?

Todos:
- [x] Research best option
- [x] Add gtag manager plugin to project
- [x] Track when users login
- [x] Track when users start a lesson
- [x] Track when users finish a lesson
- [x] Track when users visit the professor's 
- [x] Track when users visit the dorms
- [x] Track when users toggle the sound

**Comment by jsjoeio** [comment]
So there is a [plugin](https://github.com/thomascarvalho/gatsby-plugin-mixpanel) to use Mixpanel with Gatsby. But then there's also a great article for [Google Analytics with Netlify and Gatsby](https://chaseonsoftware.com/netlify-gatsby-analytics/).

**Comment by jsjoeio** [comment]
Okay glad I did my research. Apparently I'm thinking of Google Tag Manager, which will allow me to track individual events. Luckily, there is a [gatsby plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-google-gtag/) for that.

**Comment by jsjoeio** [comment]
Since I want this in immediately, I'll need to branch off `master` and merge into `master`. Keep that in mind!

**Comment by jsjoeio** [comment]
The way that it works, sending data as an event:
```js
gtag('event', 'login', {
  'method': 'Google'
});

```

**Comment by jsjoeio** [comment]
I should write a custom React effect that lets send data.

`useGTagEvent({type, event, data})`
